[[constraint]]
  name = "github.com/urfave/cli"
  version = "=1.18.1"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.8.0"

[[constraint]]
  name = "github.com/rakyll/magicmime"
  version = "=0.1.0"

[[constraint]]
  name = "github.com/rakyll/statik"
  version = "0.1.1"
